# This file is the replacement for the old alacritty.yml

[font]
size = 11.5

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 0.7

[window.padding]
x = 15
y = 15

[cursor]
style = "beam"

