# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for the "master" branch
  push:
    branches:
      - master
  pull_request:
      branches:
        - master
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run Shell Check on install.sh
        uses: AzatAI/shellcheck@v0.1.0
        with:
          path: "install.sh"
          args: "--external-sources --exclude=SC1090"

      - name: Run Shell Check on Scripts
        uses: AzatAI/shellcheck@v0.1.0
        with:
          path: "src/Scripts/**/*.sh src/Scripts/hypr src/Scripts/sandboxes src/Scripts/waybar"
          args: "--external-sources --exclude=SC1090"
