# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for the "master" branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run Shell Check
        uses: AzatAI/shellcheck@v0.1.0
        with:
          path: "*.sh src/Scripts/**/*.sh install.sh src/Scripts/hypr src/Scripts/sandboxes src/Scripts/waybar"  # Specify path to shell scripts, including those in src/Scripts, install.sh from root, src/Scripts/hypr, src/Scripts/sandboxes, and src/Scripts/waybar
          args: "--external-sources --exclude=SC1090 --exclude=SC2086"  # Double quoted to prevent globbing and word splitting  # Double quoted to prevent globbing and word splitting  # Suppress non-constant source warning SC1090
